extends Node
# Embedded GM-AI transformer inference — no Python process required.
#
# Loads gm_ai/checkpoints/weights.json (generated by export_weights.py) at
# startup and exposes a single predict() method that runs the full transformer
# forward pass in GDScript.
#
# Check `weights_loaded` before calling predict().

const WEIGHTS_PATH = "res://ai/weights.json"

var weights_loaded: bool = false

# Config read from JSON
var _D:    int = 64    # d_model
var _NH:   int = 4     # n_heads
var _DH:   int = 16    # d_head  = D / NH
var _DFF:  int = 128   # d_ff
var _T:    int = 8     # seq_len
var _F:    int = 20    # n_features
var _A:    int = 13    # n_actions
var _actions: Array = []

# Normalisation
var _norm_mean: PackedFloat32Array
var _norm_std:  PackedFloat32Array

# Weights  (PackedFloat32Array = faster element access than plain Array)
var _ip_w: PackedFloat32Array   # input_proj  (D × F) flat
var _ip_b: PackedFloat32Array   # input_proj bias (D,)
var _pe:   Array                # pos_embed   Array[PackedFloat32Array], shape (T, D)
var _fn_w: PackedFloat32Array   # final LayerNorm weight (D,)
var _fn_b: PackedFloat32Array   # final LayerNorm bias   (D,)
var _hd_w: PackedFloat32Array   # head weight (A × D) flat
var _hd_b: PackedFloat32Array   # head bias   (A,)
var _layers: Array              # Array of layer weight dicts

# ── Loading ───────────────────────────────────────────────────────────────────

func _ready() -> void:
	if not FileAccess.file_exists(WEIGHTS_PATH):
		push_warning("GmInference: weights.json not found. Run export_weights.py first.")
		return
	var f = FileAccess.open(WEIGHTS_PATH, FileAccess.READ)
	var json = JSON.parse_string(f.get_as_text())
	f.close()
	if json == null:
		push_warning("GmInference: failed to parse weights.json")
		return

	var cfg = json["config"]
	_D   = cfg["d_model"]
	_NH  = cfg["n_heads"]
	_DH  = _D / _NH
	_DFF = cfg["d_ff"]
	_T   = cfg["seq_len"]
	_F   = cfg["n_features"]
	_A   = cfg["n_actions"]
	_actions = json["actions"]

	_norm_mean = _pf(json["norm_mean"])
	_norm_std  = _pf(json["norm_std"])
	_ip_w      = _pf(json["input_proj_w"])
	_ip_b      = _pf(json["input_proj_b"])
	_fn_w      = _pf(json["final_norm_w"])
	_fn_b      = _pf(json["final_norm_b"])
	_hd_w      = _pf(json["head_w"])
	_hd_b      = _pf(json["head_b"])

	# pos_embed: list of T rows, each row length D
	_pe = []
	for row in json["pos_embed"]:
		_pe.append(_pf(row))

	# Encoder layers
	_layers = []
	for ld in json["layers"]:
		_layers.append({
			"q_w":    _pf(ld["q_w"]),
			"q_b":    _pf(ld["q_b"]),
			"k_w":    _pf(ld["k_w"]),
			"k_b":    _pf(ld["k_b"]),
			"v_w":    _pf(ld["v_w"]),
			"v_b":    _pf(ld["v_b"]),
			"out_w":  _pf(ld["out_w"]),
			"out_b":  _pf(ld["out_b"]),
			"norm1_w":_pf(ld["norm1_w"]),
			"norm1_b":_pf(ld["norm1_b"]),
			"norm2_w":_pf(ld["norm2_w"]),
			"norm2_b":_pf(ld["norm2_b"]),
			"ff1_w":  _pf(ld["ff1_w"]),
			"ff1_b":  _pf(ld["ff1_b"]),
			"ff2_w":  _pf(ld["ff2_w"]),
			"ff2_b":  _pf(ld["ff2_b"]),
		})

	weights_loaded = true
	print("GmInference: weights loaded (%d params)" % _count_params())

func _count_params() -> int:
	return _ip_w.size() + _ip_b.size() + \
		_layers.size() * (_D*_D*6 + _D*6 + _D*_DFF*2 + _DFF + _D) + \
		_fn_w.size() + _hd_w.size() + _hd_b.size()

# ── Public API ────────────────────────────────────────────────────────────────

# buffer: Array of up to SEQ_LEN snapshots (Array[float], length N_FEATURES).
# Returns: Dictionary mapping action name → weight (sums to 1.0).
func predict(buffer: Array) -> Dictionary:
	# Build normalised sequence, zero-padding on the left if buffer is short.
	var seq: Array = []
	var pad = _T - min(buffer.size(), _T)
	for _i in pad:
		seq.append(_zerof(_F))
	for i in range(max(0, buffer.size() - _T), buffer.size()):
		var raw = buffer[i]
		var tok = PackedFloat32Array()
		tok.resize(_F)
		for j in _F:
			tok[j] = (raw[j] - _norm_mean[j]) / (_norm_std[j] + 1e-8)
		seq.append(tok)

	# Input projection + positional embedding
	var h: Array = []
	for t in _T:
		var tok = _mv(_ip_w, _ip_b, seq[t], _D, _F)
		var pe: PackedFloat32Array = _pe[t]
		for i in _D:
			tok[i] += pe[i]
		h.append(tok)

	# Transformer encoder layers
	for layer in _layers:
		h = _encoder_layer(h, layer)

	# Final LayerNorm on last token
	var last = _layernorm(h[_T - 1], _fn_w, _fn_b)

	# Head + softmax
	var logits = _mv(_hd_w, _hd_b, last, _A, _D)
	var probs  = _softmax(logits)

	var result: Dictionary = {}
	for i in _A:
		result[_actions[i]] = probs[i]
	return result

# ── Transformer building blocks ───────────────────────────────────────────────

func _encoder_layer(seq: Array, L: Dictionary) -> Array:
	# Multi-head self-attention
	var attn = _mha(seq, L)

	# Residual + LayerNorm 1  (post-norm: norm after the addition)
	var h1: Array = []
	for t in _T:
		var tok = PackedFloat32Array()
		tok.resize(_D)
		for i in _D:
			tok[i] = seq[t][i] + attn[t][i]
		h1.append(_layernorm(tok, L["norm1_w"], L["norm1_b"]))

	# Feed-forward network
	var h2: Array = []
	for t in _T:
		var ffn = _ffn(h1[t], L)
		var tok = PackedFloat32Array()
		tok.resize(_D)
		for i in _D:
			tok[i] = h1[t][i] + ffn[i]
		h2.append(_layernorm(tok, L["norm2_w"], L["norm2_b"]))

	return h2

func _mha(seq: Array, L: Dictionary) -> Array:
	# Project Q, K, V for all positions
	var Q: Array = []; var K: Array = []; var V: Array = []
	for t in _T:
		Q.append(_mv(L["q_w"], L["q_b"], seq[t], _D, _D))
		K.append(_mv(L["k_w"], L["k_b"], seq[t], _D, _D))
		V.append(_mv(L["v_w"], L["v_b"], seq[t], _D, _D))

	var scale = 1.0 / sqrt(float(_DH))
	# Concatenated context across all heads, one entry per query position
	var concat: Array = []
	for t in _T:
		var c = PackedFloat32Array(); c.resize(_D); concat.append(c)

	for h in _NH:
		var h_off = h * _DH
		for i in _T:
			# Attention weights for query i over all keys
			var scores: PackedFloat32Array; scores.resize(_T)
			for j in _T:
				var dot = 0.0
				for k in _DH:
					dot += Q[i][h_off + k] * K[j][h_off + k]
				scores[j] = dot * scale
			var aw = _softmax_pf(scores)
			# Weighted value sum into concat
			for k in _DH:
				var v = 0.0
				for j in _T:
					v += aw[j] * V[j][h_off + k]
				concat[i][h_off + k] = v

	# Output projection
	var out: Array = []
	for t in _T:
		out.append(_mv(L["out_w"], L["out_b"], concat[t], _D, _D))
	return out

func _ffn(x: PackedFloat32Array, L: Dictionary) -> PackedFloat32Array:
	var h = _mv(L["ff1_w"], L["ff1_b"], x, _DFF, _D)
	for i in _DFF:
		h[i] = maxf(h[i], 0.0)   # ReLU
	return _mv(L["ff2_w"], L["ff2_b"], h, _D, _DFF)

# ── Math primitives ───────────────────────────────────────────────────────────

# Linear: W (n_out × n_in, flat row-major) × x (n_in) + b → PackedFloat32Array (n_out)
func _mv(W: PackedFloat32Array, b: PackedFloat32Array,
		x: PackedFloat32Array, n_out: int, n_in: int) -> PackedFloat32Array:
	var out = PackedFloat32Array(b)   # copy bias
	for i in n_out:
		var off = i * n_in
		var s   = 0.0
		for j in n_in:
			s += W[off + j] * x[j]
		out[i] += s
	return out

func _layernorm(x: PackedFloat32Array,
		w: PackedFloat32Array, b: PackedFloat32Array) -> PackedFloat32Array:
	var n    = x.size()
	var mean = 0.0
	for v in x: mean += v
	mean /= n
	var var_ = 0.0
	for v in x: var_ += (v - mean) * (v - mean)
	var inv_std = 1.0 / sqrt(var_ / n + 1e-5)
	var out = PackedFloat32Array(); out.resize(n)
	for i in n:
		out[i] = w[i] * (x[i] - mean) * inv_std + b[i]
	return out

# Softmax on a plain Array (used in predict() for logits)
func _softmax(x: PackedFloat32Array) -> PackedFloat32Array:
	return _softmax_pf(x)

func _softmax_pf(x: PackedFloat32Array) -> PackedFloat32Array:
	var n   = x.size()
	var mx  = x[0]
	for v in x: if v > mx: mx = v
	var out = PackedFloat32Array(); out.resize(n)
	var sum_ = 0.0
	for i in n:
		out[i] = exp(x[i] - mx)
		sum_  += out[i]
	for i in n: out[i] /= sum_
	return out

func _zerof(n: int) -> PackedFloat32Array:
	var a = PackedFloat32Array(); a.resize(n); return a

# Convert a JSON Array of numbers to PackedFloat32Array
func _pf(arr: Array) -> PackedFloat32Array:
	var out = PackedFloat32Array(); out.resize(arr.size())
	for i in arr.size(): out[i] = float(arr[i])
	return out
